//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NatilleraEntities : DbContext
    {
        public NatilleraEntities()
            : base("name=NatilleraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abono> Abonoes { get; set; }
        public virtual DbSet<Ahorro> Ahorroes { get; set; }
        public virtual DbSet<Ahorro_Evento> Ahorro_Evento { get; set; }
        public virtual DbSet<Ahorro_Usuario> Ahorro_Usuario { get; set; }
        public virtual DbSet<Aporte_Ahorro> Aporte_Ahorro { get; set; }
        public virtual DbSet<Estado_Ahorro> Estado_Ahorro { get; set; }
        public virtual DbSet<Estado_Prestamo> Estado_Prestamo { get; set; }
        public virtual DbSet<Estado_Usuario> Estado_Usuario { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Liquidacion> Liquidacions { get; set; }
        public virtual DbSet<Permiso> Permisoes { get; set; }
        public virtual DbSet<Prestamo> Prestamoes { get; set; }
        public virtual DbSet<Tipo_Ahorro> Tipo_Ahorro { get; set; }
        public virtual DbSet<Tipo_Prestamo> Tipo_Prestamo { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
