//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public System.DateTime Fecha_Prestamo { get; set; }
        public System.DateTime Fecha_Limite { get; set; }
        public double Valor_Prestamo { get; set; }
        public int Id_Tipo { get; set; }
        public double Intereses { get; set; }
        public double Valor_Real { get; set; }
        public double Total_Abonado { get; set; }
        public int Id_Estado { get; set; }
    }
}
